# Generated by Django 5.2.8 on 2025-11-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='compatible_tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
