# Generated by Django 5.2.8 on 2025-11-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compatible_years',
            field=models.CharField(blank=True, help_text='Comma-separated years, e.g. 2016, 2017, 2018', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
