# Generated by Django 5.2.8 on 2025-11-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_compatible_years_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='compatible_years',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
