# Generated by Django 5.2.8 on 2025-11-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_compatible_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='extra_voucher_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='extra_vouchers_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='five_percent_voucher_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='ten_percent_voucher_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_products_purchased',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='twenty_percent_voucher_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(default='customer', max_length=20),
        ),
    ]
