# Generated by Django 5.2.8 on 2025-11-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_profile_extra_voucher_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_car_brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_car_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_car_year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
