# Generated by Django 5.2.8 on 2025-11-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
