# Generated by Django 5.2.8 on 2025-11-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='convenience_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
