# Generated by Django 5.2.8 on 2025-11-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_order_convenience_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ten_percent_voucher_used',
            new_name='voucher_10_used',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='twenty_percent_voucher_used',
            new_name='voucher_20_used',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='five_percent_voucher_used',
            new_name='voucher_5_used',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_products_purchased',
        ),
    ]
