# Generated by Django 5.2.8 on 2025-11-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_rename_ten_percent_voucher_used_profile_voucher_10_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='five_percent_voucher_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='ten_percent_voucher_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_products_purchased',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='twenty_percent_voucher_used',
            field=models.BooleanField(default=False),
        ),
    ]
